language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: ZV/8VQbzEiNgdxa5GLJEZirnrC08gghudcIgfyMQqavD5aM171MWyAPBBsiikm7xzKQ6bKCViLNZbGQ3v6slNXxkG0XpgZz6xh2HrviQCNfVGbnI1WEdD4bX9VqastvayIdoyVy9l1jFNrULJxUIRglLFZpoyl7N2jHIuLjeyqt+aMO3hen9oSLfivIGUJ9bdNPsgdVFxigtNxa9Uz6baKN92eRWv/me0xhx2tmPg5hVzC0GUmy5GsSJSdodhjzWP74fzNd/zJfd2LJB5Q6rl0oH4RcKLk96f84bKiXaDqgBaG5t3y0B54giIPUtGdBiAEulWRUoe+GHl0OF6JwXFB8KpXulSHSjjkdNnLK3cccyI650B+WIow9XLf9h4RnvDCEXUURFTYPvMeXyCL0x8c64UEFR/uBmuMpanpigzrukbYEEa579AtTp7zqP/nysaCOrn+uvWX8aZqri21vyTR8ZVf6ILtuYKnbezjpDIXecFOVuj6JPhIw3LG536za67zUrCf60/jj5Z90mVsIiMPIpmgfJIn+9TLBmECrYTNjVqEUbhkgGvQvB/kJ06bYhCvWdG5Z+9BZPF7k1BF4hMNnwTW753m7FFdkM6m2ILSrpUSgpqd0GrOog0/dqNLd6BpZNasTzxkoumPl3aQmFF+loTWVIylpHoAuVAKdLoKA=
before_install: cd docs
on:
 branch: hotfix-release-0.0.1