spring:
  data:
    rest:
      base-path: /admin/repo

management:
  endpoints:
    web:
      base-path: /admin/actuator

mmadu:
  domainKey: 2222
  tokenService:
    url: http://localhost:10082
  userService:
    url: http://localhost:10080
