mmadu:
  home: ${user.home}/mmadu
  domainKey: 2222
  tokenService:
    url: https://mmadu-token-service.herokuapp.com
  userService:
    url: https://mmadu-user-service.herokuapp.com
spring:
  data:
    mongodb:
      uri: mongodb+srv://primedev:DWHti67pXtURNik@primedev-mongodb-orwwq.mongodb.net/mmadu_registration_db?retryWrites=true
server:
  port: ${PORT:8080}