version: '2'
services:
  mmadu-user-service:
    image: geraldoyudo/mmadu-user-service:1.2.1-SNAPSHOT
    environment:
      - mmadu.domain.encrypt-keys=${MMADU_DOMAIN_ENCRYPT_KEYS}
      - mmadu.security.master-key=${MMADU_SECURITY_MASTER_KEY}
      - mmadu.domain.api-security-enabled=${MMADU_DOMAIN_API_SECURITY_ENABLED}
      - spring.data.mongodb.host=${MONGODB_HOST}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4.20-xenial
    ports:
      - "27017:27017"