spring:
  main:
    allow-bean-definition-overriding: true
mmadu:
  token-config:
    tokens:
      - id: 0
        value: 1111
      - id: 1
        value: 1234
      - id: admin-token
        value: 2222
  domain-config:
    domains:
      - id: 1
        domainId: 0
        authenticateApiToken: 0