mmadu:
  security:
    master-key: 11111111111111111111111111111111
    domain-parsing:
      path-keys: domain,domainId,domains,appDomains
  tokenService:
    url: http://localhost:10082
  domainKey: 2222
  domain-config:
    domains:
      - id: 0
        name: sample-domain
  token-config:
    tokens:
      - id: 0
        value: 1111
      - id: admin-token
        value: 2222
spring:
  main:
    allow-bean-definition-overriding: true
