mmadu:
  security:
    master-key: 11111111111111111111111111111111
  tokenService:
    url: http://localhost:10082
  domainKey: 2222
  domain-config:
    domains:
      - id: 0
        name: sample-domain
        authenticationApiToken: 0
  token-config:
    tokens:
      - id: 0
        value: 1111
      - id: admin-token
        value: 2222
spring:
  main:
    allow-bean-definition-overriding: true