title: Mmadu
description: Documentation on all of Mmadu
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
include:
  - apis
  - blog
  - community
  - guides
  - reference
site:
  url: https://geraldoyudo.github.io/mmadu/
baseurl: /mmadu/